### ISSUE TITLE
Admin panel error

### ISSUE THREAD

**Issue by ShivamTripathi12** [jumana2000/Online-Voting-System-Using-Facial-Recognition#1]
I try to run your code by writing python manage.py runserver but when i do, no admin panel comes , only simple sign in option come for voter no button is for admin panel.Can you upload the screenshots of the admin panel or could you please upload the video of how to run the project??

**Comment by jumana2000** [comment]
Sure will upload the video

**Comment by jumana2000** [comment]
Please check for the path 
localhost:8000/admin_login
